#!/usr/bin/python3

if '__name__' == '__main__':
    from datadog import initialize, api

    print('d')
    options = {
            'api_key': '5a8cfdd01c34132a677cc362c786e335',
            'app_key': 'e68f77e76aa812b16ca68a79a480888215c54cec'
    }
    
    initialize(**options)
    get = api.DashboardList.get_items(4741)
    print('d')
    print(get['dashboards'][0]['id'])
