#!/usr/bin/env bash
# Install nginx web server  on your web-01 listening on port 80

apt-get -y update
apt-get -y install nginx
ufw allow 'Nginx HTTP'
echo "Hello World!" > /var/www/html/index.nginx-debian.html
service nginx start
