#!/usr/bin/env bash
# Configure your Nginx server to have a custom 404 page that contains the string Ceci n'est pas une page.

apt-get -y update
apt-get -y install nginx
ufw allow 'Nginx HTTP'
echo 'Hello World!' > /var/www/html/index.nginx-debian.html
mkdir /var/www/error/custom_404.html
echo "Ceci n'est pas une page" > /var/www/error/custom_404.html
sed -i "/listen 80 default_server;/a rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;/" /etc/nginx/sites-available/default
sed -i "/listen 80 default_server;/a error_page 404 /custom_404.html; location = /custom_404.html {root /var/www/error; internal; }/" /etc/nginx/sites-available/default
service nginx start
