#!/usr/bin/env bash
# configures a brand new Ubuntu machine 

apt-get -y update
apt-get -y install nginx
ufw allow 'Nginx HTTP'
sudo apt-get -y update
sudo apt-get -y install nginx
sudo sed -i "/listen 80 default_server;/a add_header X-Served-By $HOSTNAME;" /etc/nginx/sites-available/default
sudo service nginx restart
