#!/usr/bin/env bash
# Install and configure HAproxy on your lb-01 server.

sudo apt-get update
sudo add-apt-repository -y ppa:vbernat/haproxy-2.4
sudo apt-get -y install haproxy
balancer="\
frontend haproxy_balancer
    bind *:80
    default_backend servers
    
backend servers
    balance roundrobin
    server 132521-web-01 35.153.19.240:80 check
    server 132521-web-02 34.224.94.217:80 check
"
echo "$balancer" >> /etc/haproxy/haproxy.cfg
sudo service haproxy start
