#!/usr/bin/env bash
# a Bash script that generates a MySQL dump and creates a compressed archive out of it.
mysqldump -u root --password="$1" --all-databases --master-data > backup.sql
today=$(date '+%d-%m-%Y')
tar -czvf "$today.tar.gz" backup.sql
