#!/usr/bin/env bash
# Nginx must be running, and listening on port 80 of all the server’s active IPv4 IPs

sudo apt-get -y update
sudo apt-get -y install nginx

debug="\
server {
	listen 172.17.0.32:80;
	server_name a85eb2dd82d0
	root /var/www/html/index.nginx-debian.html;
}"

echo "$debug" >> /etc/nginx/sites-enabled/default
sudo service nginx restart
