#!/usr/bin/env bash
# a Bash script that displays a list of currently running processes.i
#+ Must show all processes, for all users, including those which might
#+ not have a TTY
#+ Display in a user-oriented format

ps -auxf
