#!/usr/bin/env bash
# a Bash script that displays numbers from 1 to 100.
#+ Requirements:
#+ Displays FizzBuzz when the number is a multiple of 3 and 5
#+ Displays Fizz when the number is multiple of 3
#+ Displays Buzz when the number is a multiple of 5
#+ Otherwise, displays the number

a=1
while ((a <= 100))
do
	if (( a % 3 == 0 && a % 5 == 0 ))
	then
		echo "FizzBuzz"
	elif (( a % 3 == 0 ))
	then
		echo "Fizz"
	elif (( a % 5 == 0 ))
	then
		echo "Buzz"
	else
		echo "$a"
	fi
	a=$((a+1))
done
