#!/usr/bin/env bash
# a Bash script that displays the content of the file /etc/passwd.
#+ Your script should only display:
#+ 	username
#+ 	user id
#+ 	Home directory path for the user

while read -r passwd; do
	echo "$passwd" | cut -f 1,3,6 -d:
done < "/etc/passwd"
