#!/usr/bin/env bash
# a Bash script that displays Best School 10 times, but for the 9th iteration,
#+ displays Best School and then Hi on a new line.

a=1;
while ((a <= 10))
do
	if [ $a -eq 4 ]
	then
		echo "bad luck"
	elif [ $a -eq 8 ]
	then
		echo "good luck"
	else
		echo "Best School"
	fi
	a=$((a+1))
done
